/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][8];
new PlayerText:bg[MAX_PLAYERS];

//Textdraws

//Player Textdraws
bg[playerid] = CreatePlayerTextDraw(playerid, 120.000000, 126.000000, "mdl-2006:mdc_ihbarlar");
PlayerTextDrawFont(playerid, bg[playerid], 4);
PlayerTextDrawLetterSize(playerid, bg[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, bg[playerid], 392.500000, 291.500000);
PlayerTextDrawSetOutline(playerid, bg[playerid], 1);
PlayerTextDrawSetShadow(playerid, bg[playerid], 0);
PlayerTextDrawAlignment(playerid, bg[playerid], 1);
PlayerTextDrawColor(playerid, bg[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, bg[playerid], 255);
PlayerTextDrawBoxColor(playerid, bg[playerid], 50);
PlayerTextDrawUseBox(playerid, bg[playerid], 1);
PlayerTextDrawSetProportional(playerid, bg[playerid], 1);
PlayerTextDrawSetSelectable(playerid, bg[playerid], 0);

PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 200.000000, 147.000000, "Arayan: Servis: Lokasyon: Aciklama: Tarih: Durum:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.283333, 1.049998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 226.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 248.000000, 147.000000, "#1338 Kevin_McCavish~n~Kevin_McCavish~n~Verona Mall~n~Bicakli saldiri~n~08/06/2020~n~~r~Beklemede");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.283333, 1.049998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 409.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -741092353);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 427.000000, 189.000000, "YONLEN");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.258332, 1.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 10.500000, 50.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], -2078135553);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 481.000000, 189.000000, "DETAY");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.229166, 1.799999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 10.500000, 50.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 589374975);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 1);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 200.000000, 211.000000, "Arayan: Servis: Lokasyon: Aciklama: Tarih: Durum:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.283333, 1.049998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 226.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 427.000000, 254.000000, "YONLEN");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.258332, 1.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 10.500000, 50.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], -2078135553);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 1);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 428.000000, 404.000000, "~>~");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.291666, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 10.500000, 156.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 1465342207);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 1);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 278.000000, 404.000000, "~<~");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.291666, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 10.500000, 156.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 1465342207);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
