/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][1];
new PlayerText:hud1[MAX_PLAYERS];

//Textdraws

//Player Textdraws
hud1[playerid] = CreatePlayerTextDraw(playerid, 13.000000, 166.000000, "Tahoma_~r~100_90~y~KMH/~r~92~y~MPH~n~~w~Kanal: ~y~123~n~~w~Slot: ~y~11");
PlayerTextDrawFont(playerid, hud1[playerid], 1);
PlayerTextDrawLetterSize(playerid, hud1[playerid], 0.341666, 1.750000);
PlayerTextDrawTextSize(playerid, hud1[playerid], 224.500000, 315.500000);
PlayerTextDrawSetOutline(playerid, hud1[playerid], 1);
PlayerTextDrawSetShadow(playerid, hud1[playerid], 0);
PlayerTextDrawAlignment(playerid, hud1[playerid], 1);
PlayerTextDrawColor(playerid, hud1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, hud1[playerid], 255);
PlayerTextDrawBoxColor(playerid, hud1[playerid], 50);
PlayerTextDrawUseBox(playerid, hud1[playerid], 0);
PlayerTextDrawSetProportional(playerid, hud1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, hud1[playerid], 0);

PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 13.000000, 166.000000, "N Market Street");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.341666, 1.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 224.500000, 315.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
