/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][3];
new PlayerText:bg[MAX_PLAYERS];
new PlayerText:isimbtn[MAX_PLAYERS];
new PlayerText:plakabtn[MAX_PLAYERS];
new PlayerText:aramabt[MAX_PLAYERS];
new PlayerText:yenilebtn[MAX_PLAYERS];
new PlayerText:isim_resim[MAX_PLAYERS];
new PlayerText:isim_solbilgi[MAX_PLAYERS];
new PlayerText:isim_sagbilgi[MAX_PLAYERS];
new PlayerText:isim_resimgizlikisim[MAX_PLAYERS];
new PlayerText:isim_sagbilgiadres[MAX_PLAYERS];
new PlayerText:isim_cokadres[MAX_PLAYERS];
new PlayerText:lisans_yonet[MAX_PLAYERS];
new PlayerText:sabika_ekle[MAX_PLAYERS];
new PlayerText:tutuklama_raporu[MAX_PLAYERS];
new PlayerText:kriminal_kayitlar[MAX_PLAYERS];
new PlayerText:aranma_sebebi_1[MAX_PLAYERS];

//Textdraws

//Player Textdraws
bg[playerid] = CreatePlayerTextDraw(playerid, 120.000000, 126.000000, "mdl-2005:mdc_kontrol");
PlayerTextDrawFont(playerid, bg[playerid], 4);
PlayerTextDrawLetterSize(playerid, bg[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, bg[playerid], 392.500000, 291.500000);
PlayerTextDrawSetOutline(playerid, bg[playerid], 1);
PlayerTextDrawSetShadow(playerid, bg[playerid], 0);
PlayerTextDrawAlignment(playerid, bg[playerid], 1);
PlayerTextDrawColor(playerid, bg[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, bg[playerid], 255);
PlayerTextDrawBoxColor(playerid, bg[playerid], 50);
PlayerTextDrawUseBox(playerid, bg[playerid], 1);
PlayerTextDrawSetProportional(playerid, bg[playerid], 1);
PlayerTextDrawSetSelectable(playerid, bg[playerid], 0);

isimbtn[playerid] = CreatePlayerTextDraw(playerid, 217.000000, 152.000000, "ISIM");
PlayerTextDrawFont(playerid, isimbtn[playerid], 2);
PlayerTextDrawLetterSize(playerid, isimbtn[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, isimbtn[playerid], 234.000000, 34.500000);
PlayerTextDrawSetOutline(playerid, isimbtn[playerid], 0);
PlayerTextDrawSetShadow(playerid, isimbtn[playerid], 0);
PlayerTextDrawAlignment(playerid, isimbtn[playerid], 2);
PlayerTextDrawColor(playerid, isimbtn[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, isimbtn[playerid], 255);
PlayerTextDrawBoxColor(playerid, isimbtn[playerid], 50);
PlayerTextDrawUseBox(playerid, isimbtn[playerid], 1);
PlayerTextDrawSetProportional(playerid, isimbtn[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isimbtn[playerid], 1);

plakabtn[playerid] = CreatePlayerTextDraw(playerid, 259.000000, 152.000000, "PLAKA");
PlayerTextDrawFont(playerid, plakabtn[playerid], 2);
PlayerTextDrawLetterSize(playerid, plakabtn[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, plakabtn[playerid], 234.000000, 34.500000);
PlayerTextDrawSetOutline(playerid, plakabtn[playerid], 0);
PlayerTextDrawSetShadow(playerid, plakabtn[playerid], 0);
PlayerTextDrawAlignment(playerid, plakabtn[playerid], 2);
PlayerTextDrawColor(playerid, plakabtn[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, plakabtn[playerid], 255);
PlayerTextDrawBoxColor(playerid, plakabtn[playerid], 50);
PlayerTextDrawUseBox(playerid, plakabtn[playerid], 1);
PlayerTextDrawSetProportional(playerid, plakabtn[playerid], 1);
PlayerTextDrawSetSelectable(playerid, plakabtn[playerid], 1);

aramabt[playerid] = CreatePlayerTextDraw(playerid, 284.000000, 152.000000, "test");
PlayerTextDrawFont(playerid, aramabt[playerid], 1);
PlayerTextDrawLetterSize(playerid, aramabt[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, aramabt[playerid], 461.000000, 35.500000);
PlayerTextDrawSetOutline(playerid, aramabt[playerid], 0);
PlayerTextDrawSetShadow(playerid, aramabt[playerid], 0);
PlayerTextDrawAlignment(playerid, aramabt[playerid], 1);
PlayerTextDrawColor(playerid, aramabt[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, aramabt[playerid], 255);
PlayerTextDrawBoxColor(playerid, aramabt[playerid], -1);
PlayerTextDrawUseBox(playerid, aramabt[playerid], 1);
PlayerTextDrawSetProportional(playerid, aramabt[playerid], 1);
PlayerTextDrawSetSelectable(playerid, aramabt[playerid], 1);

yenilebtn[playerid] = CreatePlayerTextDraw(playerid, 487.000000, 152.000000, "YENILE");
PlayerTextDrawFont(playerid, yenilebtn[playerid], 2);
PlayerTextDrawLetterSize(playerid, yenilebtn[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, yenilebtn[playerid], 234.000000, 35.500000);
PlayerTextDrawSetOutline(playerid, yenilebtn[playerid], 0);
PlayerTextDrawSetShadow(playerid, yenilebtn[playerid], 0);
PlayerTextDrawAlignment(playerid, yenilebtn[playerid], 2);
PlayerTextDrawColor(playerid, yenilebtn[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, yenilebtn[playerid], 255);
PlayerTextDrawBoxColor(playerid, yenilebtn[playerid], 50);
PlayerTextDrawUseBox(playerid, yenilebtn[playerid], 1);
PlayerTextDrawSetProportional(playerid, yenilebtn[playerid], 1);
PlayerTextDrawSetSelectable(playerid, yenilebtn[playerid], 1);

isim_resim[playerid] = CreatePlayerTextDraw(playerid, 128.000000, 165.000000, "Preview_Model");
PlayerTextDrawFont(playerid, isim_resim[playerid], 5);
PlayerTextDrawLetterSize(playerid, isim_resim[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, isim_resim[playerid], 231.000000, 215.000000);
PlayerTextDrawSetOutline(playerid, isim_resim[playerid], 0);
PlayerTextDrawSetShadow(playerid, isim_resim[playerid], 0);
PlayerTextDrawAlignment(playerid, isim_resim[playerid], 1);
PlayerTextDrawColor(playerid, isim_resim[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, isim_resim[playerid], 0);
PlayerTextDrawBoxColor(playerid, isim_resim[playerid], 255);
PlayerTextDrawUseBox(playerid, isim_resim[playerid], 0);
PlayerTextDrawSetProportional(playerid, isim_resim[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isim_resim[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, isim_resim[playerid], 305);
PlayerTextDrawSetPreviewRot(playerid, isim_resim[playerid], -6.000000, -1.000000, 33.000000, 0.879998);
PlayerTextDrawSetPreviewVehCol(playerid, isim_resim[playerid], 1, 1);

isim_solbilgi[playerid] = CreatePlayerTextDraw(playerid, 284.000000, 177.000000, "Isim: Numara: Sabika: Lisanslar: Adres:");
PlayerTextDrawFont(playerid, isim_solbilgi[playerid], 2);
PlayerTextDrawLetterSize(playerid, isim_solbilgi[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, isim_solbilgi[playerid], 346.000000, 35.500000);
PlayerTextDrawSetOutline(playerid, isim_solbilgi[playerid], 0);
PlayerTextDrawSetShadow(playerid, isim_solbilgi[playerid], 0);
PlayerTextDrawAlignment(playerid, isim_solbilgi[playerid], 1);
PlayerTextDrawColor(playerid, isim_solbilgi[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, isim_solbilgi[playerid], 255);
PlayerTextDrawBoxColor(playerid, isim_solbilgi[playerid], -1061109505);
PlayerTextDrawUseBox(playerid, isim_solbilgi[playerid], 0);
PlayerTextDrawSetProportional(playerid, isim_solbilgi[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isim_solbilgi[playerid], 0);

isim_sagbilgi[playerid] = CreatePlayerTextDraw(playerid, 341.000000, 177.000000, "Kevin_McCavish~n~12435243543~n~5 kodes cezasi, 1 hapis cezasi~n~Surucu, silah lisansi");
PlayerTextDrawFont(playerid, isim_sagbilgi[playerid], 1);
PlayerTextDrawLetterSize(playerid, isim_sagbilgi[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, isim_sagbilgi[playerid], 496.000000, 35.500000);
PlayerTextDrawSetOutline(playerid, isim_sagbilgi[playerid], 0);
PlayerTextDrawSetShadow(playerid, isim_sagbilgi[playerid], 0);
PlayerTextDrawAlignment(playerid, isim_sagbilgi[playerid], 1);
PlayerTextDrawColor(playerid, isim_sagbilgi[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, isim_sagbilgi[playerid], 255);
PlayerTextDrawBoxColor(playerid, isim_sagbilgi[playerid], -1061109505);
PlayerTextDrawUseBox(playerid, isim_sagbilgi[playerid], 0);
PlayerTextDrawSetProportional(playerid, isim_sagbilgi[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isim_sagbilgi[playerid], 0);

isim_resimgizlikisim[playerid] = CreatePlayerTextDraw(playerid, 245.000000, 247.000000, "_");
PlayerTextDrawFont(playerid, isim_resimgizlikisim[playerid], 1);
PlayerTextDrawLetterSize(playerid, isim_resimgizlikisim[playerid], 0.616666, 15.300003);
PlayerTextDrawTextSize(playerid, isim_resimgizlikisim[playerid], 298.500000, 83.000000);
PlayerTextDrawSetOutline(playerid, isim_resimgizlikisim[playerid], 1);
PlayerTextDrawSetShadow(playerid, isim_resimgizlikisim[playerid], 0);
PlayerTextDrawAlignment(playerid, isim_resimgizlikisim[playerid], 2);
PlayerTextDrawColor(playerid, isim_resimgizlikisim[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, isim_resimgizlikisim[playerid], 255);
PlayerTextDrawBoxColor(playerid, isim_resimgizlikisim[playerid], -572662273);
PlayerTextDrawUseBox(playerid, isim_resimgizlikisim[playerid], 1);
PlayerTextDrawSetProportional(playerid, isim_resimgizlikisim[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isim_resimgizlikisim[playerid], 0);

isim_sagbilgiadres[playerid] = CreatePlayerTextDraw(playerid, 341.000000, 215.000000, "810 Market Street~n~Marina~n~Los Santos, 313");
PlayerTextDrawFont(playerid, isim_sagbilgiadres[playerid], 1);
PlayerTextDrawLetterSize(playerid, isim_sagbilgiadres[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, isim_sagbilgiadres[playerid], 496.000000, 35.500000);
PlayerTextDrawSetOutline(playerid, isim_sagbilgiadres[playerid], 0);
PlayerTextDrawSetShadow(playerid, isim_sagbilgiadres[playerid], 0);
PlayerTextDrawAlignment(playerid, isim_sagbilgiadres[playerid], 1);
PlayerTextDrawColor(playerid, isim_sagbilgiadres[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, isim_sagbilgiadres[playerid], 255);
PlayerTextDrawBoxColor(playerid, isim_sagbilgiadres[playerid], -1061109505);
PlayerTextDrawUseBox(playerid, isim_sagbilgiadres[playerid], 0);
PlayerTextDrawSetProportional(playerid, isim_sagbilgiadres[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isim_sagbilgiadres[playerid], 1);

isim_cokadres[playerid] = CreatePlayerTextDraw(playerid, 200.000000, 247.000000, "] Bu kisi birden fazla adrese sahip, tiklayarak hepsini gorebilirsin.");
PlayerTextDrawFont(playerid, isim_cokadres[playerid], 2);
PlayerTextDrawLetterSize(playerid, isim_cokadres[playerid], 0.191663, 1.099997);
PlayerTextDrawTextSize(playerid, isim_cokadres[playerid], 505.000000, 34.500000);
PlayerTextDrawSetOutline(playerid, isim_cokadres[playerid], 0);
PlayerTextDrawSetShadow(playerid, isim_cokadres[playerid], 0);
PlayerTextDrawAlignment(playerid, isim_cokadres[playerid], 1);
PlayerTextDrawColor(playerid, isim_cokadres[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, isim_cokadres[playerid], 255);
PlayerTextDrawBoxColor(playerid, isim_cokadres[playerid], -16900353);
PlayerTextDrawUseBox(playerid, isim_cokadres[playerid], 1);
PlayerTextDrawSetProportional(playerid, isim_cokadres[playerid], 1);
PlayerTextDrawSetSelectable(playerid, isim_cokadres[playerid], 1);

lisans_yonet[playerid] = CreatePlayerTextDraw(playerid, 200.000000, 264.000000, "~>~ LISANSLARI YONET");
PlayerTextDrawFont(playerid, lisans_yonet[playerid], 2);
PlayerTextDrawLetterSize(playerid, lisans_yonet[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, lisans_yonet[playerid], 360.500000, 34.500000);
PlayerTextDrawSetOutline(playerid, lisans_yonet[playerid], 0);
PlayerTextDrawSetShadow(playerid, lisans_yonet[playerid], 0);
PlayerTextDrawAlignment(playerid, lisans_yonet[playerid], 1);
PlayerTextDrawColor(playerid, lisans_yonet[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, lisans_yonet[playerid], 255);
PlayerTextDrawBoxColor(playerid, lisans_yonet[playerid], 50);
PlayerTextDrawUseBox(playerid, lisans_yonet[playerid], 1);
PlayerTextDrawSetProportional(playerid, lisans_yonet[playerid], 1);
PlayerTextDrawSetSelectable(playerid, lisans_yonet[playerid], 1);

sabika_ekle[playerid] = CreatePlayerTextDraw(playerid, 200.000000, 281.000000, "~>~ SABIKA EKLE");
PlayerTextDrawFont(playerid, sabika_ekle[playerid], 2);
PlayerTextDrawLetterSize(playerid, sabika_ekle[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, sabika_ekle[playerid], 360.500000, 34.500000);
PlayerTextDrawSetOutline(playerid, sabika_ekle[playerid], 0);
PlayerTextDrawSetShadow(playerid, sabika_ekle[playerid], 0);
PlayerTextDrawAlignment(playerid, sabika_ekle[playerid], 1);
PlayerTextDrawColor(playerid, sabika_ekle[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, sabika_ekle[playerid], 255);
PlayerTextDrawBoxColor(playerid, sabika_ekle[playerid], 50);
PlayerTextDrawUseBox(playerid, sabika_ekle[playerid], 1);
PlayerTextDrawSetProportional(playerid, sabika_ekle[playerid], 1);
PlayerTextDrawSetSelectable(playerid, sabika_ekle[playerid], 1);

tutuklama_raporu[playerid] = CreatePlayerTextDraw(playerid, 200.000000, 298.000000, "~>~ TUTUKLAMA RAPORU YAZ");
PlayerTextDrawFont(playerid, tutuklama_raporu[playerid], 2);
PlayerTextDrawLetterSize(playerid, tutuklama_raporu[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, tutuklama_raporu[playerid], 360.500000, 34.500000);
PlayerTextDrawSetOutline(playerid, tutuklama_raporu[playerid], 0);
PlayerTextDrawSetShadow(playerid, tutuklama_raporu[playerid], 0);
PlayerTextDrawAlignment(playerid, tutuklama_raporu[playerid], 1);
PlayerTextDrawColor(playerid, tutuklama_raporu[playerid], 1296911871);
PlayerTextDrawBackgroundColor(playerid, tutuklama_raporu[playerid], 255);
PlayerTextDrawBoxColor(playerid, tutuklama_raporu[playerid], 50);
PlayerTextDrawUseBox(playerid, tutuklama_raporu[playerid], 1);
PlayerTextDrawSetProportional(playerid, tutuklama_raporu[playerid], 1);
PlayerTextDrawSetSelectable(playerid, tutuklama_raporu[playerid], 1);

kriminal_kayitlar[playerid] = CreatePlayerTextDraw(playerid, 435.000000, 264.000000, "] KRIMINAL KAYITLARI ]");
PlayerTextDrawFont(playerid, kriminal_kayitlar[playerid], 2);
PlayerTextDrawLetterSize(playerid, kriminal_kayitlar[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, kriminal_kayitlar[playerid], 577.500000, 137.500000);
PlayerTextDrawSetOutline(playerid, kriminal_kayitlar[playerid], 0);
PlayerTextDrawSetShadow(playerid, kriminal_kayitlar[playerid], 0);
PlayerTextDrawAlignment(playerid, kriminal_kayitlar[playerid], 2);
PlayerTextDrawColor(playerid, kriminal_kayitlar[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, kriminal_kayitlar[playerid], 255);
PlayerTextDrawBoxColor(playerid, kriminal_kayitlar[playerid], 858993663);
PlayerTextDrawUseBox(playerid, kriminal_kayitlar[playerid], 1);
PlayerTextDrawSetProportional(playerid, kriminal_kayitlar[playerid], 1);
PlayerTextDrawSetSelectable(playerid, kriminal_kayitlar[playerid], 1);

aranma_sebebi_1[playerid] = CreatePlayerTextDraw(playerid, 366.000000, 279.000000, "Aranma sebebi yok.");
PlayerTextDrawFont(playerid, aranma_sebebi_1[playerid], 1);
PlayerTextDrawLetterSize(playerid, aranma_sebebi_1[playerid], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, aranma_sebebi_1[playerid], 503.500000, 35.500000);
PlayerTextDrawSetOutline(playerid, aranma_sebebi_1[playerid], 0);
PlayerTextDrawSetShadow(playerid, aranma_sebebi_1[playerid], 0);
PlayerTextDrawAlignment(playerid, aranma_sebebi_1[playerid], 1);
PlayerTextDrawColor(playerid, aranma_sebebi_1[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, aranma_sebebi_1[playerid], 255);
PlayerTextDrawBoxColor(playerid, aranma_sebebi_1[playerid], -1061109505);
PlayerTextDrawUseBox(playerid, aranma_sebebi_1[playerid], 0);
PlayerTextDrawSetProportional(playerid, aranma_sebebi_1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, aranma_sebebi_1[playerid], 0);

PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 366.000000, 289.000000, "Aranma sebebi yok.");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.224996, 1.049998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 503.500000, 35.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], -1061109505);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 240.000000, 167.000000, "Profil Resmi Yok");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.483332, 2.749996);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 285.500000, 78.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 225);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 200.000000, 167.000000, "HATA: Eslesme saglanamadi.");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.191663, 1.099997);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 505.000000, 34.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], -1962934017);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], -1962934017);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
