/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][6];
new PlayerText:bg[MAX_PLAYERS];
new PlayerText:harita[MAX_PLAYERS];

//Textdraws

//Player Textdraws
bg[playerid] = CreatePlayerTextDraw(playerid, 120.000000, 126.000000, "mdl-2002:giris_mdc");
PlayerTextDrawFont(playerid, bg[playerid], 4);
PlayerTextDrawLetterSize(playerid, bg[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, bg[playerid], 392.500000, 291.500000);
PlayerTextDrawSetOutline(playerid, bg[playerid], 1);
PlayerTextDrawSetShadow(playerid, bg[playerid], 0);
PlayerTextDrawAlignment(playerid, bg[playerid], 1);
PlayerTextDrawColor(playerid, bg[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, bg[playerid], 255);
PlayerTextDrawBoxColor(playerid, bg[playerid], 50);
PlayerTextDrawUseBox(playerid, bg[playerid], 1);
PlayerTextDrawSetProportional(playerid, bg[playerid], 1);
PlayerTextDrawSetSelectable(playerid, bg[playerid], 0);

PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 196.000000, 143.000000, "~<~ Kevin McCavish Geri Don");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.170833, 1.300000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 313.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 1296911788);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 1);

harita[playerid] = CreatePlayerTextDraw(playerid, 326.000000, 145.000000, "samaps:map");
PlayerTextDrawFont(playerid, harita[playerid], 4);
PlayerTextDrawLetterSize(playerid, harita[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, harita[playerid], 181.500000, 167.000000);
PlayerTextDrawSetOutline(playerid, harita[playerid], 1);
PlayerTextDrawSetShadow(playerid, harita[playerid], 0);
PlayerTextDrawAlignment(playerid, harita[playerid], 1);
PlayerTextDrawColor(playerid, harita[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, harita[playerid], 255);
PlayerTextDrawBoxColor(playerid, harita[playerid], 50);
PlayerTextDrawUseBox(playerid, harita[playerid], 1);
PlayerTextDrawSetProportional(playerid, harita[playerid], 1);
PlayerTextDrawSetSelectable(playerid, harita[playerid], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 200.000000, 159.000000, "Secili Adres");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.245833, 1.300000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 313.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], 172);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 200.000000, 172.000000, "1403 Martin Luther King Drive~n~Idlewood Los Santos,  415~n~San Andreas");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.216667, 1.250000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 313.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 1296911788);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 200.000000, 208.000000, "Diger Adresler");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.245833, 1.300000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 313.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 172);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 200.000000, 225.000000, "- 240 Alandele Avenue");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.216667, 1.250000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 313.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 1296911788);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], -1);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 1);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 200.000000, 243.000000, "- 240 Alandele Avenue");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.216667, 1.250000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 313.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 1296911788);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */

